import './globals.css';

export const metadata = {
  title: 'Neflix Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 h-full overflow-x-hidden">{children}</body>
    </html>
  );
}
