import './globals.css';
import LocalFont from 'next/font/local';

export const metadata = {
  title: 'Neflix Clone',
  description: 'Generated by create next app',
};

const pretendard = LocalFont({
  variable: '--font-pretendard',
  src: [
    {
      path: '../../public/fonts/Pretendard-Light.woff2',
      weight: '300',
    },
    {
      path: '../../public/fonts/Pretendard-Regular.woff2',
      weight: '400',
    },
    {
      path: '../../public/fonts/Pretendard-Bold.woff2',
      weight: '700',
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-zinc-900 h-full overflow-x-hidden font-pretendard ${pretendard.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
